theme: jekyll-theme-minimal
title: NGUYEN MINH TU
description: >-
  <img src="ĐƯỜNG_DẪN_LINK_ẢNH_CÁ_NHÂN_CỦA_BẠN" width="200" style="border-radius: 8px;"><br><br>
  Data Analyst<br>
  Ho Chi Minh City
