theme: jekyll-theme-minimal
title: NGUYEN MINH TU
description: >-
  <img src="https://github.com/nguyenminhtuuuu.png" width="200" style="border-radius: 8px;"><br><br>
  Data Analyst<br>
  Ho Chi Minh City
